server:
  port: 9001


#指定注册中心地址
eureka:
  instance:
    hostname: 39.105.82.150
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/


#服务的名称
spring:
  application:
    name: parking-service
